apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
    app.kubernetes.io/managed-by: Helm
