{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: legacyops-postgres-data
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.postgres.name }}
        app.kubernetes.io/part-of: {{ .Values.app.partOf }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.targetPort }}
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: legacyops-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: legacyops-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: legacyops-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.secret.POSTGRES_USER }}
                - -d
                - {{ .Values.secret.POSTGRES_DB }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.secret.POSTGRES_USER }}
                - -d
                - {{ .Values.secret.POSTGRES_DB }}
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: legacyops-postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.postgres.name }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
