apiVersion: v1
kind: Secret
metadata:
  name: legacyops-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
