apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacyops-backend
  namespace: legacyops
  labels:
    app.kubernetes.io/name: legacyops-backend
    app.kubernetes.io/part-of: legacyops-2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: legacyops-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: legacyops-backend
        app.kubernetes.io/part-of: legacyops-2026
    spec:
      containers:
        - name: backend
          image: legacyops-backend:compose
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: legacyops-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: legacyops-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: legacyops-backend
  namespace: legacyops
  labels:
    app.kubernetes.io/name: legacyops-backend
    app.kubernetes.io/part-of: legacyops-2026
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: legacyops-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
