apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacyops-redis
  namespace: legacyops
  labels:
    app.kubernetes.io/name: legacyops-redis
    app.kubernetes.io/part-of: legacyops-2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: legacyops-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: legacyops-redis
        app.kubernetes.io/part-of: legacyops-2026
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: legacyops-redis
  namespace: legacyops
  labels:
    app.kubernetes.io/name: legacyops-redis
    app.kubernetes.io/part-of: legacyops-2026
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: legacyops-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
