apiVersion: v1
kind: Secret
metadata:
  name: legacyops-secret
  namespace: legacyops
  labels:
    app.kubernetes.io/name: legacyops
    app.kubernetes.io/part-of: legacyops-2026
type: Opaque
stringData:
  POSTGRES_DB: "legacyops"
  POSTGRES_USER: "legacyops"
  POSTGRES_PASSWORD: "legacyops"
  DATABASE_URL: "postgresql+psycopg2://legacyops:legacyops@legacyops-postgres:5432/legacyops"
